---
- name: Ensure deployment directory exists
  file:
    path: "{{ app_deployment_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv "{{ app_deployment_dir }}/venv"
  become: yes

- name: Install the application from wheel
  pip:
    virtualenv: "{{ app_deployment_dir }}/venv"
    requirements: "{{ app_deployment_dir }}/{{ wheel_file_name }}"
  become: yes

- name: Create instance directory
  file:
    path: "{{ instance_path }}"
    state: directory
    mode: '0755'
  become: yes

- name: Deploy config.py
  template:
    src: config.py.j2
    dest: "{{ instance_path }}/config.py"
  become: yes

- name: Deploy run.sh script
  template:
    src: run.sh.j2
    dest: "{{ app_deployment_dir }}/run.sh"
    mode: '0755'
  become: yes

- name: Deploy systemd service file
  template:
    src: example.service.j2
    dest: "/etc/systemd/system/example.service"
  become: yes

- name: Start the application service
  systemd:
    name: example
    state: started
    enabled: yes
  become: yes

